### ISSUE TITLE
Implementation notes: a few typos

### ISSUE THREAD

**Issue by tomwrobel** [OCFL/spec#169] opened 2018-09-28 14:07 UTC
Apologies, I'm reading the spec and noticed a few typos/bits I didn't understand. Feel free to discard.

Para 2: "Nor can these attributes be vaidated" = 'validated'

[note, not my place, but would the following not be better: "In addition, fixity checks cannot consistently validate these attributes."]

Para 3: OCFL preserves files and their content with directories serving as a useful organisational convention. 

content = contents?

I don't want to sound like an idiot, but I'm really not sure what this means. Is it that OCFL is not directly concerned with file directories? It is concerned with the preservation of files and their contents, and as such directories provide a useful organisational paradigm, but empty directories on their own are merely filesystem metadata and, as such, are not preserved.

Para 10: The correct way to do this is to create a new object the excludes the offending file with a revised version history taking this into account.

"a new object that excludes the offending file"

Also para 10:

"the same identifer as the orignal object" = the same identifier as the original object [note identifier AND original]

**Comment by tomwrobel** [comment] 2018-09-28 14:27
Also para 10: 

"the same identifer as the orignal object" = the same identifier as the original object [note identifier AND original]

**Comment by awoods** [comment] 2018-09-28 17:20
@tomwrobel : Your editorial pull-requests would be warmly welcomed.

As for `Para 3`, I believe your interpretation is what was intended:
> [OCFL] is concerned with the preservation of files and their contents, and as such directories provide a useful organisational paradigm, but empty directories on their own are merely filesystem metadata and, as such, are not preserved.

**Comment by rosy1280** [comment] 2018-10-01 15:00
@tomwrobel I believe all of your suggestions are fixed with PR #172 .  Take a look and let me know.

**Comment by tomwrobel** [comment] 2018-10-01 15:09
Line 275

- is created. The new object will be unlikely to have the same identifer as the orignal object so the deleted object can

+ is created. The new object will be unlikely to have the same identifier as the original object so the deleted object can

"identifier" and "original"

Otherwise all taken care of!

Best wishes, and blue skies

Tom
--
Tom Wrobel
Software Engineer - BDLSS
thomas.wrobel@bodleian.ox.ac.uk / 01865 277608

________________________________________

**Comment by rosy1280** [comment] 2018-10-01 15:40
fixed! and sorry, thought i got that.  closing...

**Closed by rosy1280** 2018-10-01 15:40 UTC
Labels: Editorial
